development:
  url_generator: http://www.molstr.com/users/sign_up?broker_id=
  url_shorter: http://dwz.cn/create.php
  url_params: url
  url_res: tinyurl

test:
  url_generator: http://www.molstr.com/users/sign_up?broker_id=
  url_shorter: http://urlc.cn/api.php
  url_params: turl
  url_res: tinyurl

production:
  url_generator: http://www.molstr.com/users/sign_up?broker_id=
  url_shorter: http://urlc.cn/api.php
  url_params: turl
  url_res: tinyurl
