development:
  channel_url_generator: http://jsonip.com
  channel_url_function: ip

test:
  channel_url_generator: http://188.188.114.15:8082/CRH-KH8201.action?
  channel_url_function: short_url

production:
  channel_url_generator: http://188.188.114.15:8082/CRH-KH8201.action?
  channel_url_function: short_url