class AddColumnsToProducts < ActiveRecord::Migration
  def change
     add_column :products, :产品起息日, :string
     add_column :products, :产品到期日, :string
     add_column :products, :f1, :binary
     add_column :products, :f2, :binary
     add_column :products, :f3, :binary
     add_column :products, :f1_name, :string
     add_column :products, :f2_name, :string
     add_column :products, :f3_name, :string
     add_column :products, :产品简介, :text
     add_column :products, :风险特征, :text
     add_column :products, :产品面值, :string
     add_column :products, :产品托管人, :string
     add_column :products, :链接, :string
     add_column :products, :管理期限, :text
     add_column :products, :封闭期与开放期, :text
     add_column :products, :参与和退出办理时间, :text
     add_column :products, :最低金额, :text
     add_column :products, :相关费率, :text
     add_column :products, :投资范围, :text
     add_column :products, :自有资金参与, :text
     add_column :products, :费用与业绩报酬, :text
     add_column :products, :投资经理, :text
     add_column :products, :封闭期, :text
     add_column :products, :分级结构, :text
     add_column :products, :封闭期和开放期, :text
     add_column :products, :参与和退出, :text
     add_column :products, :投资目标, :text
     add_column :products, :募集规模与存续期限, :text
     add_column :products, :投资范围及资产组合, :text
     add_column :products, :封闭期与开放日, :text
     add_column :products, :拟任投资经理, :text
     add_column :products, :业绩比较基准, :text
     add_column :products, :业绩基准, :text
     add_column :products, :募集规模与存续期间, :text
     add_column :products, :投资理念, :text
     add_column :products, :投资策略, :text
     add_column :products, :自有资金投入, :text
     add_column :products, :风险收益特征, :text
     add_column :products, :资产配置比例范围, :text
     add_column :products, :开放期, :text
     add_column :products, :产品特点, :text
     add_column :products, :参与退出费用与业绩, :text
     add_column :products, :资产配置比例, :text
     add_column :products, :参与退出费用和保护, :text
     add_column :products, :参与退出费用, :text
     add_column :products, :目标规模, :text
     add_column :products, :管理期, :text
     add_column :products, :适合推广对象, :text
     add_column :products, :集合计划份额的参与, :text
     add_column :products, :集合计划的分级, :text
     add_column :products, :集合计划份额的退出, :text
     add_column :products, :管理人自有资金参与, :text
     add_column :products, :费用, :text
     add_column :products, :业绩报酬, :text
     add_column :products, :收益分配, :text
     add_column :products, :产品展期, :text
     add_column :products, :最低份额, :text
     add_column :products, :集合计划的参与, :text
     add_column :products, :集合计划的退出, :text
     add_column :products, :管理人自有资金, :text
     add_column :products, :费用种类, :text
     add_column :products, :集合计划展期, :text
     add_column :products, :风险收益特征推广对象, :text
     add_column :products, :集合计划的展期, :text
     add_column :products, :各项费用, :text
     add_column :products, :代理推广机构, :text
  end
end